refreshInterval: 5 # number of minutes between every check
mailSubject: New IP @ Home # the subject of the email you get
smtpHost: smtp.gmail.com # smtp host
smtpPort: 587 # smtp port
smtpUser: example@gmail.com # smtp username
smtpPass: ABC12345 # smtp password
notifyAddr: myEmailAddr@example.org # which address do you want the emails to go to?
